name: Build & Push Docker Image

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      token:
        required: true
        type: string

jobs:
  build-and-push:
    name: Build and Push Job
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ inputs.username }}
          password: ${{ inputs.token }}

      - name: Build & Push Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: nzk7/personal:ci-cd-test