name: Build Docker Image & Bin File Release

on:
  push:
    tags:
      - v*

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
  bin_release:
    needs: ci
    uses: ./.github/workflows/release.yml
  docker_deployment:
    needs: ci
    uses: ./.github/workflows/docker.yml
    with:
      username: ${{ secrets.DOCKER_HUB_USERNAME }}
    secrets:
      token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}